import Head from "next/head";
import MyHeader from "../components/myheader";
import MyMain from "../components/mymain";
export default function Home() {
  return (
    <div>
      <Head>
        <title>youtube clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MyHeader />
        <MyMain />
      </main>
    </div>
  );
}
